### ISSUE TITLE
[NeoForge] Crash on startup

### ISSUE THREAD

**Issue by rfin0** [ascpixi/disconnect-packet-fix#3]
When launching a mod on NeoForge 1.21.1, a crash occurs, how to reproduce:
1. Install the NeoForge server version 21.1.80 for 1.21.1
2. Add the mod.
3. Start the server and... crash, yes.
Logs: https://mclo.gs/cSpEBDF 
Debug logs: https://mclo.gs/xi4WN34

**Comment by ascpixi** [comment]
Ah... quite a silly mistake on my part, sorry. I haven't tested the mod on NeoForge, assuming Architectury would take care of modloader parity - woops! Thanks for reporting this.

**Comment by ascpixi** [comment]
The fix was quite simple (change the mod ID to conform to NeoForge's specifications) - seems like the mod is working fine after the latest commits. Given the mixin is exactly the same as in Fabric, and only uses vanilla code, I'm going to publish this hotfix as 2.0.1.

Please don't hesitate to open another issue if any other bugs pop up! Thanks again! <3
